### ISSUE TITLE
Alt attribute usage

### ISSUE THREAD

**Issue by conneralegre** [schlumpfen/prj-rev-bwfs-dasmoto#2]
Great! I like that you used alt attributes on your images as this improves accessibility and also gives our users a description of the image.

Read more here: https://www.w3.org/wiki/HTML/Usage/TextAlternatives

Here is a more in-depth explanation on alt & accessibility if you are curious: https://webaim.org/techniques/alttext/

**Comment by schlumpfen** [comment]
Like exsample 8  in https://webaim.org/techniques/alttext/  remove alt attribut. Only decoration, no funktion.
