### ISSUE TITLE
Summary

### ISSUE THREAD

**Issue by conneralegre** [schlumpfen/prj-rev-bwfs-dasmoto#4]
Grade: **Meets Expectations**

Great job on this project! There really isn't anything wrong with it - it's meeting the specification and is following best practices in HTML and CSS. The only thing I would change about this is the formatting for the HTML, perhaps I would follow a style guide like the one provided to improve readability and organization. Next steps, I would begin to learn how to use Google Chrome Developer Tools to improve your development abilities:

 Here is a link to download Google Chrome if you do not have it: https://www.google.com/chrome/

 Here is a resource that goes over this process using Google Chrome: https://www.youtube.com/watch?v=Z3HGJsNLQ1E

**Comment by schlumpfen** [comment]
check out the dev tools of chrome.
